/* --- || PUBLIC PAGES || --- */
export { default as Home } from './Home'
export { default as About } from './About'
export { default as Portfolio } from './Portfolio'
export { default as Achievements } from './Achievements'
export { default as Legacy } from './Legacy'
export { default as Contact } from './Contact'
export { default as Rates } from './Rates'
/* --- || PRIVATE PAGES || --- */
export { default as Inbox } from './Inbox'
export { default as PhotoCMS } from './PhotoCMS'
export { default as PhotoCMSUpdate } from './PhotoCMSUpdate'
