export const ImageJSON = [
  /* Portrait */
  {
    imgSubject: 'Hannah',
    imgCaption: 'Studio - Greensboro NC',
    imgCategory: 'portrait',
    imgOrientation: 'portrait',
    imgPolaroid: true,
    source: 'https://onsmallphoto.s3.amazonaws.com/portrait-hannah-1.jpg',
  },
  {
    imgSubject: 'Misha Cordon',
    imgCaption: 'Studio - Greensboro NC',
    imgCategory: 'portrait',
    imgOrientation: 'landscape',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/portrait-misha-1.jpg',
  },
  {
    imgSubject: 'NOVA',
    imgCaption: 'Studio - Greensboro NC',
    imgCategory: 'portrait',
    imgOrientation: 'landscape',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/portrait-nova.jpg',
  },
  {
    imgSubject: 'Owen',
    imgCaption: 'Studio - Greensboro NC',
    imgCategory: 'portrait',
    imgOrientation: 'landscape',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/portrait-owen-1.jpg',
  },
  {
    imgSubject: 'Owen',
    imgCaption: 'Studio - Greensboro NC',
    imgCategory: 'portrait',
    imgOrientation: 'landscape',
    imgPolaroid: true,
    source: 'https://onsmallphoto.s3.amazonaws.com/portrait-owen-2.jpg',
  },
  {
    imgSubject: 'Pilot',
    imgCaption: 'GSO Airport',
    imgCategory: 'portrait',
    imgOrientation: 'landscape',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/portrait-pilot-1.jpg',
  },
  {
    imgSubject: 'Stereotype',
    imgCaption: 'Studio - Greensboro NC',
    imgCategory: 'portrait',
    imgOrientation: 'landscape',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/portrait-stereotype-1.jpg',
  },
  {
    imgSubject: 'Jay B',
    imgCaption: 'Studio - Greensboro NC',
    imgCategory: 'portrait',
    imgOrientation: 'portrait',
    imgPolaroid: true,
    source: 'https://onsmallphoto.s3.amazonaws.com/portrait-jay-4.jpg',
  },
  {
    imgSubject: 'Romelo',
    imgCaption: 'Studio - Greensboro NC',
    imgCategory: 'portrait',
    imgOrientation: 'landscape',
    imgPolaroid: true,
    source: 'https://onsmallphoto.s3.amazonaws.com/portrait-romelo-1.jpg',
  },
  {
    imgSubject: 'Cassie',
    imgCaption: 'Studio - Greensboro NC',
    imgCategory: 'portrait',
    imgOrientation: 'landscape',
    imgPolaroid: true,
    source: 'https://onsmallphoto.s3.amazonaws.com/portrait-cassie-1.jpg',
  },
  {
    imgSubject: 'Romelo',
    imgCaption: 'Studio - Greensboro NC',
    imgCategory: 'portrait',
    imgOrientation: 'landscape',
    imgPolaroid: true,
    source: 'https://onsmallphoto.s3.amazonaws.com/portrait-romelo-2.jpg',
  },
  /* Model */
  {
    imgSubject: 'Jay B.',
    imgCaption: 'Studio - Greensboro NC',
    imgCategory: 'model',
    imgOrientation: 'portrait',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/model-jay-2.jpg',
  },
  {
    imgSubject: 'Sirina J Gisbon',
    imgCaption: 'Bur-Mil Park',
    imgCategory: 'model',
    imgOrientation: 'landscape',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/model-sirina-2.jpg',
  },
  {
    imgSubject: 'Terrance & Kaitlyn',
    imgCaption: 'Studio - Greensboro NC',
    imgCategory: 'model',
    imgOrientation: 'landscape',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/model-tk-1.jpg',
  },
  {
    imgSubject: 'Amber',
    imgCaption: 'Studio - Greensboro NC',
    imgCategory: 'model',
    imgOrientation: 'landscape',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/model-amber-1.jpg',
  },
  {
    imgSubject: 'Amber',
    imgCaption: 'Studio - Greensboro NC',
    imgCategory: 'model',
    imgOrientation: 'portrait',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/model-amber-2.jpg',
  },
  {
    imgSubject: 'Brittany',
    imgCaption: 'Studio - Greensboro NC',
    imgCategory: 'model',
    imgOrientation: 'portrait',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/model-brittany-1.jpg',
  },
  {
    imgSubject: 'Brittany',
    imgCaption: 'Studio - Greensboro NC',
    imgCategory: 'model',
    imgOrientation: 'portrait',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/model-brittany-2.jpg',
  },
  {
    imgSubject: 'Brittany',
    imgCaption: 'Studio - Greensboro NC',
    imgCategory: 'model',
    imgOrientation: 'landscape',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/model-brittany-4.png',
  },
  {
    imgSubject: 'Casey',
    imgCaption: 'Greensboro NC',
    imgCategory: 'model',
    imgOrientation: 'landscape',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/model-casey-1.jpg',
  },
  {
    imgSubject: 'Casey',
    imgCaption: 'Greensboro NC',
    imgCategory: 'model',
    imgOrientation: 'landscape',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/model-casey-2.jpg',
  },
  {
    imgSubject: 'Jay B',
    imgCaption: 'Studio - Greensboro NC',
    imgCategory: 'model',
    imgOrientation: 'portrait',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/model-jay-3.jpg',
  },
  {
    imgSubject: 'Sirina J Gisbon',
    imgCaption: 'Bur-Mil Park',
    imgCategory: 'model',
    imgOrientation: 'landscape',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/model-sirina-1.jpg',
  },
  {
    imgSubject: 'Sirina J Gisbon',
    imgCaption: 'Greensboro NC',
    imgCategory: 'model',
    imgOrientation: 'landscape',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/model-sirina-4.jpg',
  },
  {
    imgSubject: 'Sirina J Gisbon',
    imgCaption: 'Greensboro NC',
    imgCategory: 'model',
    imgOrientation: 'landscape',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/model-sirina-5.jpg',
  },
  {
    imgSubject: 'Sirina J Gisbon',
    imgCaption: 'Greensboro NC',
    imgCategory: 'model',
    imgOrientation: 'landscape',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/model-sirina-6.jpg',
  },
  {
    imgSubject: 'Sirina J Gisbon',
    imgCaption: 'Greensboro NC',
    imgCategory: 'model',
    imgOrientation: 'portrait',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/model-sirina-7.jpg',
  },
  {
    imgSubject: 'Terrance & Kaitlyn',
    imgCaption: 'Studio - Greensboro NC',
    imgCategory: 'model',
    imgOrientation: 'landscape',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/model-tk-2.jpg',
  },
  {
    imgSubject: 'Terrance & Kaitlyn',
    imgCaption: 'Studio - Greensboro NC',
    imgCategory: 'model',
    imgOrientation: 'portrait',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/model-tk-3.jpg',
  },
  {
    imgSubject: 'Terrance & Kaitlyn',
    imgCaption: 'Greensboro NC',
    imgCategory: 'model',
    imgOrientation: 'landscape',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/model-tk-4.jpg',
  },
  {
    imgSubject: 'Billy - Nova',
    imgCaption: 'Studio - Greensboro NC',
    imgCategory: 'model',
    imgOrientation: 'portrait',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/model-billy-1.jpg',
  },
  {
    imgSubject: 'Brittany',
    imgCaption: 'Studio - Greensboro NC',
    imgCategory: 'model',
    imgOrientation: 'portrait',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/model-brittany-3.jpg',
  },
  {
    imgSubject: 'Casey',
    imgCaption: 'Greensboro NC',
    imgCategory: 'model',
    imgOrientation: 'portrait',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/model-casey-3.jpg',
  },
  {
    imgSubject: 'Casey',
    imgCaption: 'Greensboro NC',
    imgCategory: 'model',
    imgOrientation: 'portrait',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/model-casey-4.jpg',
  },
  {
    imgSubject: 'Jay B',
    imgCaption: 'Martinsville VA',
    imgCategory: 'model',
    imgOrientation: 'portrait',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/model-jay-4.jpg',
  },
  {
    imgSubject: 'Jay B',
    imgCaption: 'Bur-Mil Park',
    imgCategory: 'model',
    imgOrientation: 'landscape',
    imgPolaroid: true,
    source: 'https://onsmallphoto.s3.amazonaws.com/model-jay-5.jpg',
  },
  {
    imgSubject: 'Jay B',
    imgCaption: 'Studio - Greensboro NC',
    imgCategory: 'model',
    imgOrientation: 'portrait',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/model-jay-6.jpg',
  },
  /* Landscape */
  {
    imgSubject: 'Kure Beach',
    imgCaption: 'Kure Beach NC',
    imgCategory: 'landscape',
    imgOrientation: 'landscape',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/landscape-kure-beach.jpg',
  },
  {
    imgSubject: 'Lake Boat',
    imgCaption: 'Martinvsille NC',
    imgCategory: 'landscape',
    imgOrientation: 'landscape',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/landscape-boat.jpg',
  },
  {
    imgSubject: 'Capitol Building',
    imgCaption: 'Washington DC',
    imgCategory: 'landscape',
    imgOrientation: 'landscape',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/landscape-dc.jpg',
  },
  {
    imgSubject: "Johnny Mercer's Pier",
    imgCaption: 'Wrightsville Beach NC',
    imgCategory: 'landscape',
    imgOrientation: 'landscape',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/landscape-jmp.jpg',
  },
  {
    imgSubject: 'Our Lady of Grace',
    imgCaption: 'Greensboro NC',
    imgCategory: 'landscape',
    imgOrientation: 'landscape',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/landscape-olg.jpg',
  },
  {
    imgSubject: 'River Street',
    imgCaption: 'Wilmington NC',
    imgCategory: 'landscape',
    imgOrientation: 'portrait',
    imgPolaroid: false,
    source:
      'https://onsmallphoto.s3.amazonaws.com/landscape-wilmington-downtown.jpg',
  },
  {
    imgSubject: 'Downtown Asheville NC',
    imgCaption: 'Asheville NC',
    imgCategory: 'landscape',
    imgOrientation: 'landscape',
    imgPolaroid: true,
    source: 'https://onsmallphoto.s3.amazonaws.com/landscape-asheville-1.jpg',
  },
  {
    imgSubject: 'Downtown Asheville NC',
    imgCaption: 'Asheville NC',
    imgCategory: 'landscape',
    imgOrientation: 'landscape',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/landscape-asheville-2.jpg',
  },
  /* Event */
  {
    imgSubject: 'Chevelle',
    imgCaption: 'Greensboro NC',
    imgCategory: 'event',
    imgOrientation: 'landscape',
    imgPolaroid: true,
    source: 'https://onsmallphoto.s3.amazonaws.com/event-chevelle-1.jpg',
  },
  {
    imgSubject: 'Michael',
    imgCaption: 'North Carolina',
    imgCategory: 'event',
    imgOrientation: 'portrait',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/event-michael.jpg',
  },
  {
    imgSubject: 'Our Lady Of Grace - Fall Festival',
    imgCaption: 'Greensboro NC',
    imgCategory: 'event',
    imgOrientation: 'landscape',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/event-olg-1.jpg',
  },
  {
    imgSubject: 'David',
    imgCaption: 'PBC - Gibsonville NC',
    imgCategory: 'event',
    imgOrientation: 'landscape',
    imgPolaroid: true,
    source: 'https://onsmallphoto.s3.amazonaws.com/event-pb-1.jpg',
  },
  {
    imgSubject: 'Paint Ball',
    imgCaption: 'PBC - Gibsonville NC',
    imgCategory: 'event',
    imgOrientation: 'landscape',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/event-pb-2.jpg',
  },
  /* Wedding */
  {
    imgSubject: "Nelson's Wedding",
    imgCaption: 'Martinsville VA',
    imgCategory: 'wedding',
    imgOrientation: 'landscape',
    imgPolaroid: true,
    source: 'https://onsmallphoto.s3.amazonaws.com/wedding-nelson-rings.jpg',
  },
  {
    imgSubject: "Tori's Wedding",
    imgCaption: 'Wilmington NC',
    imgCategory: 'wedding',
    imgOrientation: 'portrait',
    imgPolaroid: true,
    source: 'https://onsmallphoto.s3.amazonaws.com/wedding-tori.jpg',
  },
  {
    imgSubject: "Tori's Wedding",
    imgCaption: 'Wilmington NC',
    imgCategory: 'wedding',
    imgOrientation: 'landscape',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/wedding-tori-1.jpg',
  },
  /* Cosplay */
  {
    imgSubject: 'Link - Jay B',
    imgCaption: 'Martinsville VA',
    imgCategory: 'cosplay',
    imgOrientation: 'portrait',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/cosplay-jay-link-1.jpg',
  },
  {
    imgSubject: 'Link - Jay B',
    imgCaption: 'Martinsville VA',
    imgCategory: 'cosplay',
    imgOrientation: 'portrait',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/cosplay-jay-link-2.jpg',
  },
  {
    imgSubject: 'Link - Jay B',
    imgCaption: 'Studio - Greensboro NC',
    imgCategory: 'cosplay',
    imgOrientation: 'portrait',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/cosplay-jay-link-3.jpg',
  },
  {
    imgSubject: 'Link - Jay B',
    imgCaption: 'Studio - Greensboro NC',
    imgCategory: 'cosplay',
    imgOrientation: 'landscape',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/cosplay-jay-link-4.jpg',
  },
  /* Prodcut */
  {
    imgSubject: 'Jay B',
    imgCaption: 'Studio - Greensboro NC',
    imgCategory: 'product',
    imgOrientation: 'landscape',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/product-jay-1.jpg',
  },
  {
    imgSubject: 'Washington Apple',
    imgCaption: 'Wilmington NC',
    imgCategory: 'product',
    imgOrientation: 'landscape',
    imgPolaroid: false,
    source:
      'https://onsmallphoto.s3.amazonaws.com/product-washington-apple.jpg',
  },
  /* Nature | Pets */
  {
    imgSubject: 'Snow Dogs',
    imgCaption: 'Greensboro NC',
    imgCategory: 'product',
    imgOrientation: 'landscape',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/nature-snow-dogs.jpg',
  },
  {
    imgSubject: 'Ducks',
    imgCaption: 'Greensboro NC',
    imgCategory: 'product',
    imgOrientation: 'landscape',
    imgPolaroid: true,
    source: 'https://onsmallphoto.s3.amazonaws.com/nature-ducks.jpg',
  },
  {
    imgSubject: 'Flower',
    imgCaption: 'Greensboro NC',
    imgCategory: 'product',
    imgOrientation: 'landscape',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/nature-flower.jpg',
  },
  /* Boudoir */
  {
    imgSubject: 'Misha',
    imgCaption: 'Greensboro NC',
    imgCategory: 'boudoir',
    imgOrientation: 'landscape',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/boudoir-misha-1.jpg',
  },
  {
    imgSubject: 'Misha',
    imgCaption: 'Greensboro NC',
    imgCategory: 'boudoir',
    imgOrientation: 'portrait',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/boudoir-misha-2.jpg',
  },
  /* Award Winning */
  {
    imgSubject: 'Dusty',
    imgCaption: 'Martinsville VA',
    imgCategory: 'award',
    imgOrientation: 'landscape',
    imgPolaroid: false,
    source: 'https://onsmallphoto.s3.amazonaws.com/award-dusty.jpg',
  },
]
